config/routes.rb
  Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :likes, only: [:create, :destroy]
    post 'likes2' => 'likes2#create', as: 'likes2'
    delete 'like2' => 'likes2#destroy', as: 'like2'
    resources :comments, only: [:create]
  end
  get 'post/test' => 'posts#test'
  get 'post/new2' => 'posts#new2', as: 'new_post2'
  
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'user/:id/post' => 'users#post', as: 'user_post'
  get 'user/:id/like_post' => 'users#like_post', as: 'user_like_post'
  get 'user/:id/favorite_post' => 'users#favorite_post', as: 'user_favorite_post'

  resources :books, only: [:index, :new]
  get 'books/search' => 'books#search'
  get 'books/create' => 'books#create'

  get '/post/hashtag/:name', to: "posts#hashtag"

  root 'hello#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		user_like_count = @post.likes.where(user_id: current_user.id).count
		if user_like_count <=99
			like = current_user.likes.create(post_id: params[:post_id])
		end
	end
	def destroy
		@post = Post.find(params[:post_id])
		like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
		like.destroy
	end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<div class="icons">
    <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
            <div class="icon">
                <%= link_to post_likes_path(id: post.id, post_id: post.id), method: :post, remote: true do %>
                    <i class="fas fa-thumbs-up"></i><%= post.likes.count %>
                <% end %>
            </div>
        <% else %>
            <div class="icon">
                <%= link_to post_likes_path(id: post.id, post_id: post.id), method: :post, remote: true do %>
                    <i class="far fa-thumbs-up"></i><%= post.likes.count %>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <div class="icon">
            <i class="far fa-thumbs-up"></i><%= post.likes.count %>
        </div>
    <% end %>
    
    <div class="icon">
        <%= link_to  post_path(post.id) do %>
            <i class="fas fa-file-alt"></i>
        <% end %>
    </div>
    <% if user_signed_in? && current_user.id == post.user_id %>
        <div class="icon">
            <%= link_to edit_post_path(post.id) do %>
                <i class="fas fa-pen"></i>
            <% end %>
        </div>
        <div class="icon">
            <%= link_to post_path(post.id), method: :delete, data: { confirm: '削除しますか？' } do %>
                <i class="fas fa-trash-alt"></i>
            <% end %>
        </div>
    <% else %>
        <div class="vacant-icon"></div>
        <div class="vacant-icon"></div>
    <% end %>
</div>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/index.html.erb
<i class="far fa-heart"></i><%= @post.likes.count %><br>
<i class="far fa-heart"></i><%= @like_count %><br>
<i class="far fa-heart"></i><%= @user_like_count %><br>