config/routes.rb
  Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :likes, only: [:create, :destroy]
    post 'likes2' => 'likes2#create', as: 'likes2'
    delete 'like2' => 'likes2#destroy', as: 'like2'
    resources :comments, only: [:create]
  end
  get 'post/test' => 'posts#test'
  get 'post/new2' => 'posts#new2', as: 'new_post2'
  
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'user/:id/post' => 'users#post', as: 'user_post'
  get 'user/:id/like_post' => 'users#like_post', as: 'user_like_post'
  get 'user/:id/favorite_post' => 'users#favorite_post', as: 'user_favorite_post'

  resources :books, only: [:index, :new]
  get 'books/search' => 'books#search'
  get 'books/create' => 'books#create'

  get '/post/hashtag/:name', to: "posts#hashtag"

  root 'hello#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  mount_uploader :image, ImageUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  validates :name, presence: true
  validates :profile, length: { maximum: 200 }
  
  has_many :posts, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post
  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :comments, dependent: :destroy

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
    def profile
        @user = User.find(params[:id])
    end
    def post
        @user = User.find(params[:id])
        @posts = @user.posts
        @posts = @posts.page(params[:page]).per(10)
    end
    def like_post
        @user = User.find(params[:id])
        @likes = @user.likes.select(:post_id).distinct
        @likes = @likes.page(params[:page]).per(10)
    end
    def favorite_post
        @user = User.find(params[:id])
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def render_with_hashtags(caption)
        caption.gsub(/[#＃][\w\p{Han}ぁ-ヶｦ-ﾟー]+/){|word| link_to word, "/post/hashtag/#{word.delete("#")}"}.html_safe
    end 
end

app/views/users/favorite_post.html.erb
<div class="user-container">    
    <%= link_to user_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "プロフィールへ" %>
        </div>
    <% end %>
    <%= link_to user_post_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "自身の投稿へ" %>
        </div>
    <% end %>
    <%= link_to user_like_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "いいねした投稿" %>
        </div>
    <% end %>
    <%= link_to user_favorite_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "フォローしたユーザーの投稿" %>
        </div>
    <% end %>
</div>
<div class="index-posts-container">
    <h3>フォローしたユーザーの投稿</h3>
    <% @user.followings.each do |following| %>
        <% following.posts.each do |post| %>
            <div class="index-post">
                <div class="index-main-box">
                    <div class="index-left-container">
                        <%= link_to user_path(post.user.id) do %>
                            <div class="user-icon">
                                <div class="index-user-image">
                                    <%= image_tag post.user.image_url, class: "image" if post.user.image? %>
                                </div>
                                <div><%= post.user.name %></div>
                            </div>
                        <% end %>
                        <div class="index-comment-box">
                            <%= post.title %><br>
                            <%= render_with_hashtags(safe_join(post.comment.split("\n"),tag(:br))) %>
                            <div id="likes_buttons_<%= post.id %>">
                                <%= render partial: 'likes/like', locals: { post: post } %>
                            </div>
                        </div>
                        <p class="time"><%= post.created_at %></p>
                    </div>
                    <div class="index-right-container">
                        <% if post.thumbnail? %>
                            <%= image_tag post.thumbnail_url, class: 'index-image' %>
                        <% else %>
                            <%= image_tag post.image_url, class: 'index-image' if post.image? %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/users/like_post.html.erb
<div class="user-container">    
    <%= link_to user_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "プロフィールへ" %>
        </div>
    <% end %>
    <%= link_to user_post_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "自身の投稿へ" %>
        </div>
    <% end %>
    <%= link_to user_like_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "いいねした投稿" %>
        </div>
    <% end %>
    <%= link_to user_favorite_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "フォローしたユーザーの投稿" %>
        </div>
    <% end %>
</div>
<div class="index-posts-container">
    <%= page_entries_info @likes %>
        <h3>いいねした投稿</h3>
        <% @likes.each do |like| %>
            <div class="index-post">
                <div class="index-main-box">
                    <div class="index-left-container">
                        <%= link_to user_path(like.post.user.id) do %>
                            <div class="user-icon">
                                <div class="index-user-image">
                                    <%= image_tag like.post.user.image_url, class: "image" if like.post.user.image? %>
                                </div>
                                <div><%= like.post.user.name %></div>
                            </div>
                        <% end %>
                        <div class="index-comment-box">
                            <%= like.post.title %><br>
                            <%= render_with_hashtags(safe_join(like.post.comment.split("\n"),tag(:br))) %>
                            <div id="likes_buttons_<%= like.post.id %>">
                                <%= render partial: 'likes/like', locals: { post: like.post } %>
                            </div>
                        </div>
                        <p class="time"><%= like.post.created_at %></p>
                    </div>
                    <div class="index-right-container">
                        <% if like.post.thumbnail? %>
                            <%= image_tag like.post.thumbnail_url, class: 'index-image' %>
                        <% else %>
                            <%= image_tag like.post.image_url, class: 'index-image' if like.post.image? %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <%= paginate @likes %>
</div>

app/views/users/post.html.erb
<div class="user-container">    
    <%= link_to user_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "プロフィールへ" %>
        </div>
    <% end %>
    <%= link_to user_post_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "自身の投稿へ" %>
        </div>
    <% end %>
    <%= link_to user_like_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "いいねした投稿" %>
        </div>
    <% end %>
    <%= link_to user_favorite_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "フォローしたユーザーの投稿" %>
        </div>
    <% end %>
</div>
<div class="index-posts-container">
    <%= page_entries_info @posts %>
        <h3>このユーザーの投稿</h3>
        <% @posts.each do |post| %>
            <div class="index-post">
                <div class="index-main-box">
                    <div class="index-left-container">
                        <%= link_to user_path(post.user.id) do %>
                            <div class="user-icon">
                                <div class="index-user-image">
                                    <%= image_tag post.user.image_url, class: "image" if post.user.image? %>
                                </div>
                                <div><%= post.user.name %></div>
                            </div>
                        <% end %>
                        <div class="index-comment-box">
                            <%= post.title %><br>
                            <%= render_with_hashtags(safe_join(post.comment.split("\n"),tag(:br))) %>
                            <div id="likes_buttons_<%= post.id %>">
                                <%= render partial: 'likes/like', locals: { post: post } %>
                            </div>
                        </div>
                        <p class="time"><%= post.created_at %></p>
                    </div>
                    <div class="index-right-container">
                        <% if post.thumbnail? %>
                            <%= image_tag post.thumbnail_url, class: 'index-image' %>
                        <% else %>
                            <%= image_tag post.image_url, class: 'index-image' if post.image? %>
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <%= paginate @posts %>
</div>

app/views/users/show.html.erb
<div class="user-container">    
    <%= link_to user_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "プロフィールへ" %>
        </div>
    <% end %>
    <%= link_to user_post_path(id: @user.id) do %>
        <div class="btn btn-primary" >
            <%= "自身の投稿へ" %>
        </div>
    <% end %>
    <%= link_to user_like_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "いいねした投稿" %>
        </div>
    <% end %>
    <%= link_to user_favorite_post_path(id: @user.id) do %>
        <div class="btn btn-primary">
            <%= "フォロワーの投稿" %>
        </div>
    <% end %>
</div>

<div class="profile-container">
    <div class="user-icon">
        <div class="user-image">
            <%= image_tag @user.image_url, class: "image" if @user.image? %>
        </div>
        <div class="user_info">
            <div><%= @user.name %></div>
            <div><%= @user.profile %></div>
        </div>
    </div>
    <% if current_user.id == @user.id %>
        <%= link_to "編集する", edit_user_registration_path %><br>
    <% end %>
    <% if current_user.following?(@user) %>
        <%= link_to "フォロー外す", user_relationship_path(@user.id), method: :delete %>
    <% else %>
        <%= link_to "フォローする", user_relationships_path(@user.id), method: :post %>
    <% end %>
</div>


<div class="following-container">
    <h2>フォロー</h2>
    <% @user.followings.each do |following| %>
        <%= link_to user_path(following.id) do %>
            <div class="user-icon">
                <div class="index-user-image">
                    <%= image_tag following.image_url, class: "image" if following.image? %>
                </div>
                <div><%= following.name %></div>
            </div>
        <% end %>
    <% end %>
</div>
<div class="follower-container">
    <h2>フォロワー</h2>
    <% @user.followers.each do |follower| %>
        <%= link_to user_path(follower.id) do %>
                <div class="user-icon">
                    <div class="index-user-image">
                        <%= image_tag follower.image_url, class: "image" if follower.image? %>
                    </div>
                    <div><%= follower.name %></div>
                </div>
        <% end %>
    <% end %>
</div>