config/routes.rb
  Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :likes, only: [:create, :destroy]
    post 'likes2' => 'likes2#create', as: 'likes2'
    delete 'like2' => 'likes2#destroy', as: 'like2'
    resources :comments, only: [:create]
  end
  get 'post/test' => 'posts#test'
  get 'post/new2' => 'posts#new2', as: 'new_post2'
  
  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  get 'user/:id/post' => 'users#post', as: 'user_post'
  get 'user/:id/like_post' => 'users#like_post', as: 'user_like_post'
  get 'user/:id/favorite_post' => 'users#favorite_post', as: 'user_favorite_post'

  resources :books, only: [:index, :new]
  get 'books/search' => 'books#search'
  get 'books/create' => 'books#create'

  get '/post/hashtag/:name', to: "posts#hashtag"

  root 'hello#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>まんがらいふ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/earlyaccess/nicomoji.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <h1>まんがらいふ</h1>
      <div id="header-list", onmouseover="mouseover();">
        <ul>
          <div><li><%= link_to "投稿一覧", posts_path %></li></div>
          <div><li><%= link_to "新規投稿", new_post_path %></li></div>
          <div><li><%= link_to "検索", books_search_path %></li></div>
          <% if user_signed_in? %>
            <div><li><%= link_to "マイページへ", user_path(current_user.id) %></li></div>
            <div><li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li></div>
          <% end %>
        </ul>
      </div>
      <div id="header-list2", onmouseleave="mouseleave();">
        <ul>
          <div>
            <li><%= link_to "投稿一覧", posts_path %></li>
            <li><%= link_to "新しい順", posts_path %></li>
            <li><%= link_to "古い順", posts_path(id:2) %></li>
          </div>
          <div>
          <li><%= link_to "新規投稿", new_post_path %></li>
          </div>
          <div>
          <li><%= link_to "検索", books_search_path %></li>
          </div>
          <% if user_signed_in? %>
            <div>
              <li><%= link_to "マイページ", user_path(current_user.id) %></li>
              <li><%= link_to "ユーザーの投稿", user_post_path(id: current_user.id) %></li>
              <li><%= link_to "いいねした投稿", user_like_post_path(id: current_user.id) %></li>
              <li><%= link_to "フォロワーの投稿", user_favorite_post_path(id: current_user.id) %></li>
            </div>
            <div>
            <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            </div>
          <% end %>
        </ul>
      </div>
      <script>
          document.getElementById("header-list2").style.display="none";

          function mouseover(){
              const p1 =document.getElementById("header-list2");
              const p2 =document.getElementById("header-list");

              p1.style.display = "block";
              p2.style.display = "none";
          }
          function mouseleave(){
              const p1 =document.getElementById("header-list2");
              const p2 =document.getElementById("header-list");

              p1.style.display = "none";
              p2.style.display = "block";
          }
      </script>
    </header>
    <main>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </main>
    <div class"push"></div>
    <footer>
      <p>Copyright © IinoKazuki All Rights Reserved.</p>
    </footer>
  </body>
</html>